version: '3'
services:
  web:
    build: .
    expose:
      - "8000"
    ports:
      - "8000:8000"
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    depends_on:
      - "elasticsearch"
    networks:
      - "elastic"

  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.7.0"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      discovery.type: single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - "elastic"

  kibana:
    image: "docker.elastic.co/kibana/kibana:7.7.0"
    ports:
      - "5601:5601"
    links:
      - "elasticsearch"
    networks:
      - "elastic"

volumes:
  data01:
    driver: local
  data02:
    driver: local
  data03:
    driver: local

networks:
  elastic:
    driver: bridge